export const GET_SIGN_IN_REQUEST = 'GET_SIGN_IN_REQUEST ';
export const GET_SIGN_IN_SUCCESS = 'GET_SIGN_IN_SUCCESS';
export const GET_SIGN_IN_FAILURE = 'GET_SIGN_IN_FAILURE';

export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST ';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';

export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST ';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST ';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST ';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
