export const GET_SIGN_IN_REQUEST = 'GET_SIGN_IN_REQUEST ';
export const GET_SIGN_IN_SUCCESS = 'GET_SIGN_IN_SUCCESS';
export const GET_SIGN_IN_FAILURE = 'GET_SIGN_IN_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';

export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST ';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAILURE = 'VALIDATE_TOKEN_FAILURE';
