export const GET_POPULAR_NOVELS_REQUEST = 'GET_POPULAR_NOVELS_REQUEST ';
export const GET_POPULAR_NOVELS_SUCCESS = 'GET_POPULAR_NOVELS_SUCCESS';
export const GET_POPULAR_NOVELS_FAILURE = 'GET_POPULAR_NOVELS_FAILURE';

export const GET_NOVELS_REQUEST = 'GET_NOVELS_REQUEST ';
export const GET_NOVELS_SUCCESS = 'GET_NOVELS_SUCCESS';
export const GET_NOVELS_FAILURE = 'GET_NOVELS_FAILURE';

export const GET_NOVEL_REQUEST = 'GET_NOVEL_REQUEST ';
export const GET_NOVEL_SUCCESS = 'GET_NOVEL_SUCCESS';
export const GET_NOVEL_FAILURE = 'GET_NOVEL_FAILURE';

export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS';
export const GET_CHAPTER_FAILURE = 'GET_CHAPTER_FAILURE';
