export const GET_POPULAR_NOVELS_REQUEST = 'GET_POPULAR_NOVELS_REQUEST ';
export const GET_POPULAR_NOVELS_SUCCESS = 'GET_POPULAR_NOVELS_SUCCESS';
export const GET_POPULAR_NOVELS_FAILURE = 'GET_POPULAR_NOVELS_FAILURE';
