export const GET_POPULAR_NOVELS_REQUEST = 'GET_POPULAR_NOVELS_REQUEST ';
export const GET_POPULAR_NOVELS_SUCCESS = 'GET_POPULAR_NOVELS_SUCCESS';
export const GET_POPULAR_NOVELS_FAILURE = 'GET_POPULAR_NOVELS_FAILURE';

export const GET_RECOMMENDED_NOVELS_REQUEST = 'GET_RECOMMENDED_NOVELS_REQUEST ';
export const GET_RECOMMENDED_NOVELS_SUCCESS = 'GET_RECOMMENDED_NOVELS_SUCCESS';
export const GET_RECOMMENDED_NOVELS_FAILURE = 'GET_RECOMMENDED_NOVELS_FAILURE';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST ';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

export const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST ';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

export const GET_NOVELS_REQUEST = 'GET_NOVELS_REQUEST ';
export const GET_NOVELS_SUCCESS = 'GET_NOVELS_SUCCESS';
export const GET_NOVELS_FAILURE = 'GET_NOVELS_FAILURE';

export const GET_NOVEL_REQUEST = 'GET_NOVEL_REQUEST ';
export const GET_NOVEL_SUCCESS = 'GET_NOVEL_SUCCESS';
export const GET_NOVEL_FAILURE = 'GET_NOVEL_FAILURE';

export const LIKE_CHAPTER_REQUEST = 'LIKE_CHAPTER_REQUEST ';
export const LIKE_CHAPTER_SUCCESS = 'LIKE_CHAPTER_SUCCESS';
export const LIKE_CHAPTER_FAILURE = 'LIKE_CHAPTER_FAILURE';

export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS';
export const GET_CHAPTER_FAILURE = 'GET_CHAPTER_FAILURE';
